services:
  backend_service:
    container_name: backend
    image: vectornguyen76/resume_ranking_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.local
      - ./analysis_service/.env  # Including analysis_service env if needed
    restart: on-failure
    volumes:
      - ./backend/logs:/app/logs
      - ./analysis_service/logs:/app/logs/analysis  # Merging analysis logs into backend logs
      - ./analysis_service/candidate_cv:/app/candidate_cv  # Candidate CV volume
    depends_on:
      - mongo_db

  mongo_db:
    container_name: mongo_db
    image: mvertes/alpine-mongo:latest
    volumes:
      - mongo_data:/data/db/
    restart: always
    ports:
      - 27017:27017

  

volumes:
  mongo_data:
